// <auto-generated />
using System;
using DecorRental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DecorRental.Infrastructure.Migrations
{
    [DbContext(typeof(DecorRentalDbContext))]
    [Migration("20260222235747_StockBasedInventoryModel")]
    partial class StockBasedInventoryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DecorRental.Domain.Entities.CategoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KitCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("KitCategoryId", "ItemTypeId")
                        .IsUnique();

                    b.ToTable("CategoryItems", (string)null);
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.ItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ItemTypes", (string)null);
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.KitCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KitCategories", (string)null);
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.KitTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KitThemes", (string)null);
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KitCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KitThemeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KitCategoryId");

                    b.HasIndex("KitThemeId");

                    b.HasIndex("Status", "KitThemeId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.ReservationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationItems", (string)null);
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.CategoryItem", b =>
                {
                    b.HasOne("DecorRental.Domain.Entities.ItemType", null)
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DecorRental.Domain.Entities.KitCategory", null)
                        .WithMany("Items")
                        .HasForeignKey("KitCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("DecorRental.Domain.Entities.KitCategory", null)
                        .WithMany()
                        .HasForeignKey("KitCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DecorRental.Domain.Entities.KitTheme", null)
                        .WithMany("Reservations")
                        .HasForeignKey("KitThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DecorRental.Domain.ValueObjects.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("StartDate");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.ReservationItem", b =>
                {
                    b.HasOne("DecorRental.Domain.Entities.ItemType", null)
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DecorRental.Domain.Entities.Reservation", null)
                        .WithMany("Items")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.KitCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.KitTheme", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DecorRental.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
