namespace DecorRental.Api.Contracts;

public sealed record ContractDataRequest(
    Guid KitThemeId,
    Guid ReservationId,
    string KitThemeName,
    string KitCategoryName,
    DateOnly ReservationStartDate,
    DateOnly ReservationEndDate,
    string CustomerName,
    string CustomerDocumentNumber,
    string CustomerPhoneNumber,
    string CustomerAddress,
    string? CustomerZipCode = null,
    string? CustomerStreet = null,
    string? CustomerNumber = null,
    string? CustomerComplement = null,
    string? CustomerState = null,
    string? CustomerReference = null,
    string? CustomerNeighborhood = null,
    string? CustomerCity = null,
    string? Notes = null,
    bool HasBalloonArch = false,
    bool IsEntryPaid = false,
    DateOnly ContractDate = default,
    decimal? TotalAmount = null,
    decimal? EntryAmount = null);

public sealed record ContractDataResponse(
    Guid KitThemeId,
    Guid ReservationId,
    string KitThemeName,
    string KitCategoryName,
    DateOnly ReservationStartDate,
    DateOnly ReservationEndDate,
    string CustomerName,
    string CustomerDocumentNumber,
    string CustomerPhoneNumber,
    string CustomerAddress,
    string? CustomerZipCode = null,
    string? CustomerStreet = null,
    string? CustomerNumber = null,
    string? CustomerComplement = null,
    string? CustomerState = null,
    string? CustomerReference = null,
    string? CustomerNeighborhood = null,
    string? CustomerCity = null,
    string? Notes = null,
    bool HasBalloonArch = false,
    bool IsEntryPaid = false,
    DateOnly ContractDate = default,
    decimal? TotalAmount = null,
    decimal? EntryAmount = null);
