namespace DecorRental.Application.UseCases.ReserveKit;

public sealed record ReserveKitResult(
    Guid ReservationId,
    Guid KitThemeId,
    Guid KitCategoryId,
    DateOnly StartDate,
    DateOnly EndDate,
    string ReservationStatus,
    bool IsStockOverride,
    string? StockOverrideReason,
    string CustomerName,
    string CustomerDocumentNumber,
    string CustomerPhoneNumber,
    string CustomerAddress,
    string? CustomerZipCode,
    string? CustomerStreet,
    string? CustomerNumber,
    string? CustomerComplement,
    string? CustomerNeighborhood,
    string? CustomerCity,
    string? CustomerState,
    string? CustomerReference,
    string? Notes,
    bool HasBalloonArch,
    bool IsEntryPaid);
